zynq-safemode-cfgs: fix variable not defined error
The var NILRT_ARM_MIGRATION_SUPPORTED_DEVICES is defined in another
layer and if missing, bitbake will error while parsing this recipe with:

Exception: AttributeError: 'NoneType' object has no attribute 'split'

Fix by assinging to "" if the variable was undefined, instead of None.

Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>